version: '3.8'

services:
  server-admin:
#    build: ./server
#    command: "go run main.go"
#    image : fandinxr/golang
    image: golang-sap:5mar23
    restart: always
    container_name: server-admin-0
    ports:
      - 5355:5300
    networks:
      - mysql-8

  client-admin:
    image: react-sap:7mar23
    restart: always
    container_name: client-admin-0
    ports:
      - 3000:3000
    networks:
      - mysql-8





networks:
  mysql-8:
    external: true

