version: '3.3'
services:
  mysql:
    container_name: mysql-8
    image: mysql:8.0.32-debian
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'mysqlpassword'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3333:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - mysql-8
    #restart: always

# Names our volume
volumes:
  my-db:

networks:
  mysql-8:
    external: true
